CREATE DATABASE db;
USE db;

CREATE TABLE IF NOT EXISTS MemberShipTypes (
    id INT AUTO_INCREMENT,
    typeName VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS GymMemberShip (
    id INT AUTO_INCREMENT,
    typeId INT NOT NULL,
    numOfTrainings SMALLINT NOT NULL,
    dateOfSale DATE,
    FOREIGN KEY (typeId) REFERENCES MemberShipTypes(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS SportType (
    id INT AUTO_INCREMENT,
    typeName VARCHAR(30) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS SportForm (
    id INT AUTO_INCREMENT,
    sportFormName VARCHAR(30) NOT NULL,
    sportTypeId INT NOT NULL,
    FOREIGN KEY (sportTypeId) REFERENCES SportType(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS FormMembershipRelation (
    id INT AUTO_INCREMENT,
    GMSId INT NOT NULL,
    sportFormId INT NOT NULL,

    FOREIGN KEY (GMSId) REFERENCES GymMemberShip(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (sportFormId) REFERENCES SportForm(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Treners (
    id INT AUTO_INCREMENT,
    firstName VARCHAR(20) NOT NULL,
    middleName VARCHAR(20) NOT NULL,
    lastName VARCHAR(20) NOT NULL,

    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS TrenerSportRelation (
    id INT AUTO_INCREMENT,
    sportFormId INT NOT NULL,
    trenerId INT NOT NULL,

    FOREIGN KEY (trenerId) REFERENCES Treners(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (sportFormId) REFERENCES SportForm(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    PRIMARY KEY (id)
);